server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/photolancer
    username: root
    password: 1234
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: false
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
logging.level:
  org.hibernate.SQL: debug