server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/photo_lancer'
    username: 'root'
    password: '@Ekdldjxm0525'
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: false
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug